on:
  push:
    branches:
      - main
      - ci-cd

jobs:
  build-chrome-extension:
    name: Build Chrome extension artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |-
          yarn install
          yarn build
          zip -r chrome-extension-${{ github.sha }}.zip dist

      - name: Archive chrome-extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension-${{ github.sha }}
          path: chrome-extension-${{ github.sha }}.zip

  # api usage reference:
  # * <https://developer.chrome.com/docs/webstore/using_webstore_api/>
  # * <https://github.com/fregante/chrome-webstore-upload/blob/main/How%20to%20generate%20Google%20API%20keys.md>
  upload-extension:
    name: Upload extension
    runs-on: ubuntu-latest
    needs: build-chrome-extension
    env:
      # you can optionally specify extension ID here, we do this so that
      # all of our environments (dev, staging, prod) have a consistent ID
      # we can reference. Otherwise the extension ID is autogenerated.
      EXTENSION_ID: kipleafooljlggggpiinilijkokogbkb
      CI_GOOGLE_CLIENT_ID: 223096084109-sbsu3q198082ecu10so7lh8eap1ei6oh.apps.googleusercontent.com
      CI_GOOGLE_CLIENT_SECRET: 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
      CI_GOOGLE_REFRESH_TOKEN: 1//034jNq5K7iNjbCgYIARAAGAMSNwF-L9IrZf4wjYu0SMvNLHrON95u1PNwBEtK86MePeh_gJw7azoBnDy2KEMPodtVHP3HXUMh2vA

    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16.10'

      - name: Download bundle artifact
        uses: actions/download-artifact@v3
        with:
          name: chrome-extension-${{ github.sha }}

      - name: Install webstore cli
        run: |-
          npm install -g chrome-webstore-upload-cli

      - name:
          Upload step
          # $ chrome-webstore-upload upload --source extension.zip --extension-id $EXTENSION_ID --client-id $CLIENT_ID --client-secret $CLIENT_SECRET --refresh-token $REFRESH_TOKEN
        run: |-
          chrome-webstore-upload upload --source chrome-extension-${{ github.event.pull_request.head.sha }}.zip --extension-id ${{ env.EXTENSION_ID }} --client-id ${{ env.CI_GOOGLE_CLIENT_ID }} --client-secret ${{ env.CI_GOOGLE_CLIENT_SECRET }} --refresh-token ${{ env.CI_GOOGLE_REFRESH_TOKEN }}
