on:
  push:
    branches:
      - main
      
jobs:
  build-and-upload:
    name: Build and Upload Chrome Extension
    runs-on: ubuntu-latest
    env:
      EXTENSION_ID: kipleafooljlggggpiinilijkokogbkb
      CI_GOOGLE_CLIENT_ID: ${{ secrets.CI_GOOGLE_CLIENT_ID }}
      CI_GOOGLE_CLIENT_SECRET: ${{ secrets.CI_GOOGLE_CLIENT_SECRET }}
      CI_GOOGLE_REFRESH_TOKEN: ${{ secrets.CI_GOOGLE_REFRESH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '16.10'

      - name: Build Extension
        run: |-
          yarn install
          yarn build
          zip -r chrome-extension-${{ github.sha }}.zip dist

      - name: Install webstore cli
        run: npm install -g chrome-webstore-upload-cli

      - name: Upload to Chrome Web Store
        run: |-
          chrome-webstore-upload upload --source chrome-extension-${{ github.sha }}.zip --extension-id ${{ env.EXTENSION_ID }} --client-id ${{ env.CI_GOOGLE_CLIENT_ID }} --client-secret ${{ env.CI_GOOGLE_CLIENT_SECRET }} --refresh-token ${{ env.CI_GOOGLE_REFRESH_TOKEN }}
