on:
  push:
    branches:
      - main

env:
  EXTENSION_ID: kipleafooljlggggpiinilijkokogbkb
  CI_GOOGLE_CLIENT_ID: ${{ secrets.CI_GOOGLE_CLIENT_ID }}
  CI_GOOGLE_CLIENT_SECRET: ${{ secrets.CI_GOOGLE_CLIENT_SECRET }}
  CI_GOOGLE_REFRESH_TOKEN: ${{ secrets.CI_GOOGLE_REFRESH_TOKEN }}
      
jobs:
  build-and-upload:
    name: Build and Upload Chrome Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.17'  

      - name: Build Extension
        run: |-
          yarn install
          yarn build
          zip -r chrome-extension-${{ github.sha }}.zip dist

      - name: Install webstore cli
        run: npm install -g chrome-webstore-upload-cli

      - name: Debug Secrets
        run: |-
          echo "Extension ID: $EXTENSION_ID"
          echo "Client ID exists: $(if [ ! -z "$CI_GOOGLE_CLIENT_ID" ]; then echo 'Yes'; else echo 'No'; fi)"
          echo "Client Secret exists: $(if [ ! -z "$CI_GOOGLE_CLIENT_SECRET" ]; then echo 'Yes'; else echo 'No'; fi)"
          echo "Refresh Token exists: $(if [ ! -z "$CI_GOOGLE_REFRESH_TOKEN" ]; then echo 'Yes'; else echo 'No'; fi)"

      - name: Upload to Chrome Web Store
        run: |-
          chrome-webstore-upload upload \
            --source chrome-extension-${{ github.sha }}.zip \
            --extension-id "$EXTENSION_ID" \
            --client-id "$CI_GOOGLE_CLIENT_ID" \
            --client-secret "$CI_GOOGLE_CLIENT_SECRET" \
            --refresh-token "$CI_GOOGLE_REFRESH_TOKEN"
